version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - app-network

  dotnet-api:
    image: ghcr.io/kodekloudsiva/siva-dotnet-api:v20250822173126
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OrdersDb;User Id=sa;Password=${SA_PASSWORD};
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - app-network

volumes:
  sqlserverdata:

networks:
  app-network:
