name: "DB Apply Migrations"
description: "Apply EF Core migration SQL scripts to a database"

inputs:
  sql-host:
    description: "Database host"
    required: true
  sql-port:
    description: "Database port"
    required: true
  sql-db:
    description: "Database name"
    required: true
  sql-user:
    description: "Database user"
    required: true
  sql-pass:
    description: "Database password"
    required: true
  cicd-sql:
    description: "Path to cicd/sql directory"
    required: true
  runner-download-migrations:
    description: "migration script generated in previous job will be downloaded in this runner machines directory"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: db-migration-scripts
        path: sql-migration-scripts

    - name: Run SQL Applier to apply migration
      env:
        MIGRATION_SQL: ${{ github.workspace }}/sql-migration-scripts/migration.sql
      shell: bash
      run: |
        echo "🚀 Running SQL Applier with $MIGRATION_SQL"
        docker run --rm \
          -e DB_HOST="${{ inputs.sql-host }},${{ inputs.sql-port }}" \
          -e DB_NAME=${{ inputs.sql-db }} \
          -e DB_USER=${{ inputs.sql-user }} \
          -e DB_PASS="${{ inputs.sql-pass }}" \
          -v "${{ env.MIGRATION_SQL }}:/app/migration.sql" \
          -v "${{ github.workspace }}/cicd/scripts/migration-entrypoint.sh:/app/migration-entrypoint.sh:ro" \
          mcr.microsoft.com/mssql-tools:latest \
          /bin/bash /app/migration-entrypoint.sh
