name: Build MS SQL & DOTNET API Workflow

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Download source files
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: tmp get path and list directory
        run: |
             pwd && ls -lrta
          
      - name: Build and push ms sql image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ./ms-sql/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/siva-ms-sql:v${{ env.TIMESTAMP }}
      
      - name: Build and push dotnet api image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ./dotnet-api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/siva-dotnet-api:v${{ env.TIMESTAMP }}
          
