name: DOTNET Build API

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Download source files
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: Set environment variable for image tag
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/DOTNET_IMAGE_TAG \
            -d '{"name":"DOTNET_IMAGE_TAG","value":"${{ github.ref_name }}-v-${{ github.run_number }}"}'

          
      #- name: Build and push ms sql image to GitHub Container Registry
      #  uses: docker/build-push-action@v6
      #  with:
      #    context: ./ms-sql
      #    file: ./ms-sql/Dockerfile
      #    push: true
      #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/siva-ms-sql:v${{ env.TIMESTAMP }}
      #    build-args: |
      #      SA_PASSWORD=${{ secrets.SA_PASSWORD }}
      
      - name: Build and push dotnet api image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dotnet-api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/siva-dotnet-api:${{ vars.DOTNET_IMAGE_TAG }}
          
