name: Build MS SQL & DOTNET API Workflow

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Download source files
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      
      - name: 🔧 Set image tag
        run: echo "DOTNET_IMAGE_TAG=${{ github.ref_name }}-v-${{ github.run_number }}" >> $GITHUB_ENV

      - name: Save tag for downstream workflows
        run: echo "{{ env.DOTNET_IMAGE_TAG }}"
        run: echo "{{ env.DOTNET_IMAGE_TAG }}" > DOTNET_IMAGE_TAG.txt

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: DOTNET_IMAGE_TAG
          path: DOTNET_IMAGE_TAG.txt


          
      #- name: Build and push ms sql image to GitHub Container Registry
      #  uses: docker/build-push-action@v6
      #  with:
      #    context: ./ms-sql
      #    file: ./ms-sql/Dockerfile
      #    push: true
      #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/siva-ms-sql:v${{ env.TIMESTAMP }}
      #    build-args: |
      #      SA_PASSWORD=${{ secrets.SA_PASSWORD }}
      
      - name: Build and push dotnet api image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dotnet-api/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/siva-dotnet-api:${{ env.DOTNET_IMAGE_TAG }}
          
